version: '3.8'
services:
  admin-cloud:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && ng serve --host 0.0.0.0 --poll=200"

